import { StyleSheet, Platform } from 'react-native';
import colors from '../../../colors/colors';


const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    pagePad: { paddingHorizontal: 16 },
    header: { marginBottom: 8, marginTop: 12 },
    title: { fontSize: 22, fontWeight: '700', alignItems: 'center', justifyContent: 'center', },
    headerSubtitle: { color: colors.textSecondary, marginTop: 4 },
    searchBar: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: 10,
        paddingHorizontal: 10,
        paddingVertical: Platform.OS === 'ios' ? 10 : 6,
        marginBottom: 12,
    },
        searchIcon: { marginRight: 8, fontSize: 18 },
        input: { flex: 1, fontSize: 16, color: '#111' },
        card: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: colors.primary,
            padding: 12,
            borderRadius: 10,
            marginBottom: 10,
            shadowColor: '#000',
            shadowOpacity: 0.06,
            shadowRadius: 6,
            elevation: 2,
        },
        cardLeft: { marginRight: 12 },
        avatar: {
            width: 44,
            height: 44,
            borderRadius: 22,
            backgroundColor: colors.card,
            alignItems: 'center',
            justifyContent: 'center',
            fontWeight: '700',
        },
        avatarText: { fontWeight: '700', color: colors.text },
        cardBody: { flex: 1 },
        itemTitle: { fontSize: 16, fontWeight: '700' },
        itemDescription: { color: colors.textSecondary, marginTop: 2, fontSize: 13 },
        itemSubtitle: { color: colors.textSecondary, marginTop: 4, fontSize: 13 },
        itemContact: { color: colors.textSecondary, marginTop: 2, fontSize: 12 },
        cardRight: { alignItems: 'flex-end' },
        chevron: { fontSize: 22, color: 'black' },
        empty: { padding: 24, alignItems: 'center' },
        emptyText: { fontSize: 16, color: colors.text, marginBottom: 16 },
        reloadButton: {
            backgroundColor: colors.primary,
            paddingVertical: 10,
            paddingHorizontal: 20,
            borderRadius: 8,
            marginTop: 8,
        },
        reloadButtonText: { color: colors.text, fontWeight: '600' },
        loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
        loadingText: { marginTop: 12, color: colors.textSecondary },
        // Modal styles
        modalOverlay: {
            flex: 1,
            backgroundColor: 'rgba(0, 0, 0, 0.5)',
            justifyContent: 'flex-end',
        },
        modalContent: {
            backgroundColor: colors.background,
            borderTopLeftRadius: 20,
            borderTopRightRadius: 20,
            maxHeight: '85%',
            paddingBottom: Platform.OS === 'ios' ? 34 : 20,
        },
        modalHeader: {
            alignItems: 'center',
            paddingTop: 24,
            paddingHorizontal: 20,
            paddingBottom: 16,
            borderBottomWidth: 1,
            borderBottomColor: colors.textSecondary + '20',
        },
        modalAvatarLarge: {
            width: 80,
            height: 80,
            borderRadius: 40,
            backgroundColor: colors.primary,
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 12,
        },
        modalAvatarText: {
            fontSize: 32,
            fontWeight: '700',
            color: colors.text,
        },
        modalTitle: {
            fontSize: 24,
            fontWeight: '700',
            color: colors.text,
            textAlign: 'center',
        },
        modalBody: {
            paddingHorizontal: 20,
            paddingTop: 20,
        },
        modalSection: {
            marginBottom: 20,
        },
        modalSectionTitle: {
            fontSize: 16,
            fontWeight: '700',
            color: colors.text,
            marginBottom: 8,
        },
        modalText: {
            fontSize: 15,
            color: colors.textSecondary,
            lineHeight: 22,
        },
        modalActions: {
            paddingHorizontal: 20,
            paddingTop: 10,
            gap: 12,
        },
        modalButtonPrimary: {
            backgroundColor: colors.primary,
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: 'center',
            shadowColor: '#000',
            shadowOpacity: 0.1,
            shadowRadius: 8,
            elevation: 3,
        },
        modalButtonPrimaryText: {
            color: colors.text,
            fontSize: 16,
            fontWeight: '700',
        },
        modalButtonSecondary: {
            backgroundColor: colors.card,
            paddingVertical: 16,
            borderRadius: 12,
            alignItems: 'center',
        },
        modalButtonSecondaryText: {
            color: colors.text,
            fontSize: 16,
            fontWeight: '600',
        },
});
export default styles;