import { StyleSheet, Platform } from 'react-native';
import colors from '../../../colors/colors';


const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    pagePad: { paddingHorizontal: 16 },
    header: { marginBottom: 8 },
    title: { fontSize: 22, fontWeight: '700', alignItems: 'center', justifyContent: 'center', },
    headerSubtitle: { color: colors.textSecondary, marginTop: 4 },
    shortcutsRow: { flexDirection: 'row', marginVertical: 12 },
        shortcut: {
            backgroundColor: colors.card,
            paddingVertical: 10,
            paddingHorizontal: 16,
            borderRadius: 24,
            marginRight: 10,
            shadowColor: '#000',
            shadowOpacity: 0.06,
            shadowRadius: 4,
            elevation: 1,
        },
        shortcutText: { color: colors.text, fontWeight: '700' },
        searchBar: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: colors.card,
            borderRadius: 10,
            paddingHorizontal: 10,
            paddingVertical: Platform.OS === 'ios' ? 10 : 6,
            marginBottom: 12,
        },
        searchIcon: { marginRight: 8, fontSize: 18 },
        input: { flex: 1, fontSize: 16, color: '#111' },
        card: {
            flexDirection: 'row',
            alignItems: 'center',
            backgroundColor: colors.primary,
            padding: 12,
            borderRadius: 10,
            marginBottom: 10,
            shadowColor: '#000',
            shadowOpacity: 0.06,
            shadowRadius: 6,
            elevation: 2,
        },
        cardLeft: { marginRight: 12 },
        avatar: {
            width: 44,
            height: 44,
            borderRadius: 22,
            backgroundColor: colors.card,
            alignItems: 'center',
            justifyContent: 'center',
            fontWeight: '700',
        },
        avatarText: { fontWeight: '700', color: colors.text },
        cardBody: { flex: 1 },
        itemTitle: { fontSize: 16, fontWeight: '700' },
        itemSubtitle: { color: colors.textSecondary, marginTop: 4 },
        cardRight: { alignItems: 'flex-end' },
        chevron: { fontSize: 22, color: 'black' },
        empty: { padding: 24, alignItems: 'center' },
});
export default styles;